server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-map?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root@123

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8858
  application:
    name: service-map

#自定义
amap:
  key: 33484ab1266b2677596b06b39e7e7d92
  sid: 1009030
